from dsabackend.src.controllers.default_controller import DefaultController
from dsabackend.src.controllers.users_controller import UsersController
from dsabackend.src.controllers.auth_controller import AuthController
from dsabackend.src.controllers.roles_controller import RolesController
from dsabackend.src.controllers.admissions_controller import AdmissionsController
from dsabackend.src.controllers.subjects_controller import SubjectsController
from dsabackend.src.controllers.areas_controller import AreasController
