"""empty message

Revision ID: 314df61e1da5
Revises: c8dcf5f79923
Create Date: 2018-08-12 19:41:01.861290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314df61e1da5'
down_revision = 'c8dcf5f79923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_credits', sa.Integer(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=False),
    sa.Column('amount_of_weeks', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['Graduate_Programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subjects')
    # ### end Alembic commands ###
