"""empty message

Revision ID: 670ff977720d
Revises: f8495391b812
Create Date: 2018-08-13 16:58:01.877210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670ff977720d'
down_revision = 'f8495391b812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admissions', sa.Column('current_semester', sa.Integer(), nullable=False))
    op.add_column('Subjects', sa.Column('subject_semester', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Subjects', 'subject_semester')
    op.drop_column('Admissions', 'current_semester')
    # ### end Alembic commands ###
