"""empty message

Revision ID: 99a8f756a161
Revises: 670ff977720d
Create Date: 2018-08-13 17:42:49.195305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a8f756a161'
down_revision = '670ff977720d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Subject_Statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('Admission_Subject_Relations',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['Admissions.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Subject_Statuses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['Subjects.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'admission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Admission_Subject_Relations')
    op.drop_table('Subject_Statuses')
    # ### end Alembic commands ###
