"""empty message

Revision ID: d0c8780d8f52
Revises: 99a8f756a161
Create Date: 2018-08-14 13:06:58.523488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c8780d8f52'
down_revision = '99a8f756a161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Revoke_Tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Revoke_Tokens')
    # ### end Alembic commands ###
