"""empty message

Revision ID: f4e34f12d22d
Revises: 1780b74ecbc5
Create Date: 2018-08-13 12:10:20.946501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e34f12d22d'
down_revision = '1780b74ecbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admissions', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admissions', 'id')
    # ### end Alembic commands ###
